GET http://localhost:8080/users

###

POST http://localhost:8080/users
content-type: application/json

{
    "studentname": "Michael",
    "studentsurname": "Dave",
    "studentclass": "SS3",
    "studentdept": "science"
}